#!/usr/bin/env python3
"""Reproduce W1 Latin composition and box-drawing tables from Unicode 17.0.0."""
import argparse
import hashlib
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
DATA = Path(__file__).resolve().parent / 'unicode-17.0.0'
PINS = {'UnicodeData.txt': '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c',
        'LICENSE.txt': 'e7a93b009565cfce55919a381437ac4db883e9da2126fa28b91d12732bc53d96'}
OUT = ROOT / 'abi/include/os64/text_w1_data.h'

def generate():
    for name, digest in PINS.items():
        if hashlib.sha256((DATA/name).read_bytes()).hexdigest() != digest:
            raise ValueError('unexpected pinned input: '+name)
    rows = [line.split(';') for line in (DATA/'UnicodeData.txt').read_text().splitlines()]
    assert all(len(r)==15 for r in rows)
    latin=[]; pairs=[]; boxes=[]
    for row in rows:
        cp=int(row[0],16)
        if 0xC0<=cp<=0x17F and row[2].startswith('L'): latin.append(cp)
        parts=row[5].split()
        if 0xC0<=cp<=0x17F and len(parts)==2 and not parts[0].startswith('<'):
            base,mark=map(lambda x:int(x,16),parts)
            if (65<=base<=90 or 97<=base<=122) and 0x300<=mark<=0x36F: pairs.append((base,mark,cp))
        if 0x2500<=cp<=0x257F:
            name=row[1].removeprefix('BOX DRAWINGS ')
            arms=[0]*4; dash=arc=diag=0
            words=name.split(); default=0
            weight={'LIGHT':1,'HEAVY':2,'SINGLE':1,'DOUBLE':3}
            if words[0] in weight: default=weight[words.pop(0)]
            if 'DASH' in words:
                dash={'DOUBLE':2,'TRIPLE':3,'QUADRUPLE':4}[words[0]];words=words[2:]
            if words and words[0]=='ARC':arc=1;words=words[1:]
            if words and words[0]=='DIAGONAL':
                diag={'UPPER RIGHT TO LOWER LEFT':1,'UPPER LEFT TO LOWER RIGHT':2,'CROSS':3}[' '.join(words[1:])]
            else:
                dirs={'UP':[0],'RIGHT':[1],'DOWN':[2],'LEFT':[3],'VERTICAL':[0,2],'HORIZONTAL':[1,3]}
                for part in ' '.join(words).split(' AND '):
                    tokens=part.split();w=next((weight[t] for t in tokens if t in weight),default)
                    assert w, name
                    for token in tokens:
                        if token in weight:continue
                        assert token in dirs,(name,token)
                        for d in dirs[token]:arms[d]=w
            boxes.append((cp,arms,dash,arc,diag))
    assert len(boxes)==128 and len(set((b,m) for b,m,c in pairs))==len(pairs)
    out=['/* Generated by tools/fonts/generate_w1.py; Unicode 17.0.0, Unicode License v3. */',
         '#ifndef OS64_TEXT_W1_DATA_H','#define OS64_TEXT_W1_DATA_H',
         'static const uint16_t text_latin_letters[] = {',
         ','.join('0x%04x'%c for c in latin),'};',
         'static const struct { uint16_t base, mark, composed; } text_compositions[] = {']
    out += ['    {0x%x,0x%x,0x%x},'%p for p in sorted(pairs)]
    out += ['};','static const struct { uint8_t arms[4], dash, arc, diagonal; } text_boxes[128] = {']
    out += ['    {{%s},%d,%d,%d}, /* U+%04X */'%(','.join(map(str,a)),d,r,g,c) for c,a,d,r,g in boxes]
    out += ['};','#endif','']
    return '\n'.join(out), len(pairs), len(latin)

def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    text,pairs,letters=generate()
    if a.check:
        if OUT.read_text()!=text:raise SystemExit('generated W1 table differs')
    else:OUT.write_text(text)
    print(f'PASS: pinned Unicode inputs; {pairs} compositions, {letters} Latin letters, 128 box descriptions')
if __name__=='__main__':main()
