// df_test — the DIRECTION FLAG must not cross a ring boundary.
//
// `std` is an ordinary unprivileged instruction. Nothing stops a ring-3
// program from setting DF and then entering the kernel, and the x86-64 System V
// ABI says DF is CLEAR at every function entry — which is precisely why the
// compiler emits a bare `rep movsq` for a struct copy with no `cld` in front of
// it. The flag is a precondition somebody else owes. If the kernel does not
// establish it on entry, those copies run BACKWARD.
//
// This is not decorative: the os64 kernel binary carries twelve `rep movsq`
// even at -O0, and three of them are inside proc_gen_maps — reached by an
// unprivileged read() of /proc/<pid>/maps.
//
// TWO BOUNDARIES, TWO MECHANISMS, and this fixture checks both:
//
//   1. RING 3 -> KERNEL. SYSCALL clears only the RFLAGS bits named in SFMASK,
//      and DF was not among them until 2026-08-24. Interrupt and exception
//      gates never clear DF at all, so their entry stubs do it with `cld`.
//      Checked here end-to-end: open and read the same file with DF clear and
//      with DF set, and insist the kernel produced identical bytes.
//
//      BE HONEST ABOUT WHAT THIS HALF PROVES, because it is less than it
//      looks. Run against a kernel with the DF mask deliberately removed, it
//      still PASSES — so it is a regression guard on observable behaviour,
//      not a demonstration of the mechanism. The mechanism itself is not in
//      doubt (the SDM is explicit that SYSCALL clears only the FMASK bits,
//      and the kernel carries twelve register-counted `rep movsq`), but no
//      reachable one of them was shown to produce different bytes with DF
//      set. Whether that is because those particular copies are short, or
//      because the paths this fixture reaches do not include them, was not
//      established. The mask is closed anyway — it is one bit and it is what
//      the ABI requires — but nobody should read a green here as proof that
//      the hole was exploitable. Part 2 below is the half with a real
//      negative control.
//
//   2. KERNEL -> A SIGNAL HANDLER. A handler is an ordinary C function the
//      kernel calls out of nowhere, so it is owed the same clear DF. All three
//      delivery paths used to enter it on the interrupted RFLAGS (Codex #29
//      rd10). Checked here directly: the handler reads its own flags, and the
//      interrupted code insists DF came BACK afterwards — because sigreturn
//      must restore what it interrupted, DF included. Clearing on entry and
//      restoring on return are two different promises and this tests both.
//
// Every `std` below is followed IMMEDIATELY by the syscall, in one asm block,
// so no compiler-generated string operation ever runs while the flag is set.
// Setting DF and then calling a C function would be testing the bug with the
// bug.
//
// Exit codes 0x0DF000xx ("DF"; the step is the low byte):
//   0x0DF00000  success
//   0x0DF00001  /proc/self/maps could not be opened or read
//   0x0DF00002  the kernel returned DIFFERENT bytes with DF set (it ran backward)
//   0x0DF00003  the SIGINT handler could not be installed
//   0x0DF00004  the handler never ran
//   0x0DF00005  the handler was entered with DF SET (the ABI is violated)
//   0x0DF00006  DF was not restored after sigreturn (the frame lost a flag)

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include "os64/os64.h"
#include "os64/signal.h"
#include "os64/syscall_numbers.h"

#define STEP(n)   (0x0DF00000u | (uint32_t)(n))
#define RFLAGS_DF (1ULL << 10)

static volatile uint64_t gFlagsInHandler = 0;
static volatile int      gHandlerRan     = 0;

static char gClean[2048];
static char gDirty[2048];

static void on_sigint(int signo)
{
    // FIRST instruction of the handler, before anything the compiler might
    // turn into a string operation: what flags were we entered with?
    uint64_t f;
    __asm__ volatile("pushfq\n\tpop %0" : "=r"(f) :: "memory");
    gFlagsInHandler = f;
    gHandlerRan = signo;
}

static void die(uint32_t step, const char *why)
{
    os64_printf("df_test: %s\n", why);
    os64_serial_log(why);
    os64_exit(STEP(step));
}

// One read() through a raw syscall, optionally with DF set across it. The
// `std` and the `syscall` are adjacent by construction; `cld` restores sanity
// the instant we are back, before any C can run.
// One open() through a raw syscall, optionally with DF set across it.
//
// THE OPEN IS THE ONE THAT MATTERS, and finding that out cost a wrong control
// run: /proc content is generated by proc_gen_maps from proc_open, not from
// the read — the read merely copies out of a buffer that already exists. A
// first version of this fixture set DF across the READ only, never made the
// kernel execute a single `rep movsq` with the flag set, and passed just as
// happily on a kernel with the mask removed. A test that cannot fail proves
// nothing; both syscalls carry the flag now.
static int64_t open_with_df(const char *path, const char *mode, bool set_df)
{
    int64_t h;
    if (set_df) {
        __asm__ volatile(
            "std\n\t"
            "syscall\n\t"
            "cld\n\t"
            : "=a"(h)
            : "a"((uint64_t)SYSCALL_OPEN), "D"((uint64_t)(uintptr_t)path),
              "S"((uint64_t)(uintptr_t)mode)
            : "rcx", "r11", "memory");
    } else {
        __asm__ volatile(
            "syscall\n\t"
            : "=a"(h)
            : "a"((uint64_t)SYSCALL_OPEN), "D"((uint64_t)(uintptr_t)path),
              "S"((uint64_t)(uintptr_t)mode)
            : "rcx", "r11", "memory");
    }
    return h;
}

static int64_t read_with_df(int32_t h, char *buf, size_t len, bool set_df)
{
    // ARG 3 IS THE READ'S PATIENCE, AND IT RIDES IN R10 (abi
    // syscall_numbers.h — 0 means POLL since the 2026-08-05 ruling, not
    // "forever"). Hand-rolling this syscall means hand-rolling that too:
    // leaving r10 as whatever happened to be in it is how this fixture first
    // read zero bytes and blamed the direction flag. os64_read's own stub
    // carries a comment about exactly this register.
    register uint64_t r10 __asm__("r10") = OS64_WAIT_FOREVER;
    int64_t got;
    if (set_df) {
        __asm__ volatile(
            "std\n\t"
            "syscall\n\t"
            "cld\n\t"
            : "=a"(got)
            : "a"((uint64_t)SYSCALL_READ), "D"((uint64_t)(uint32_t)h),
              "S"((uint64_t)(uintptr_t)buf), "d"((uint64_t)len), "r"(r10)
            : "rcx", "r11", "memory");
    } else {
        __asm__ volatile(
            "syscall\n\t"
            : "=a"(got)
            : "a"((uint64_t)SYSCALL_READ), "D"((uint64_t)(uint32_t)h),
              "S"((uint64_t)(uintptr_t)buf), "d"((uint64_t)len), "r"(r10)
            : "rcx", "r11", "memory");
    }
    return got;
}

int main(void)
{
    // ── 1. RING 3 -> KERNEL ────────────────────────────────────────────────
    // /proc/<pid>/maps specifically, because proc_gen_maps is where three of
    // the kernel's twelve inlined `rep movsq` live. Same file, same offset,
    // read twice: once honestly, once with DF set across the syscall.
    int64_t h1 = open_with_df("/proc/self/maps", "r", false);
    if (h1 < 0)
        die(1, "df_test: could not open /proc/self/maps");
    int64_t n1 = read_with_df((int32_t)h1, gClean, sizeof(gClean), false);
    os64_close((int32_t)h1);

    // Both syscalls with DF set: the OPEN is where proc_gen_maps runs its
    // `rep movsq`, the READ is where the bytes come back.
    int64_t h2 = open_with_df("/proc/self/maps", "r", true);
    if (h2 < 0)
        die(1, "df_test: could not re-open /proc/self/maps");
    int64_t n2 = read_with_df((int32_t)h2, gDirty, sizeof(gDirty), true);
    os64_close((int32_t)h2);

    if (n1 <= 0 || n2 <= 0)
        die(1, "df_test: /proc/self/maps read returned nothing");
    if (n1 != n2)
        die(2, "df_test: the kernel returned a DIFFERENT LENGTH with DF set");
    for (int64_t i = 0; i < n1; i++)
        if (gClean[i] != gDirty[i])
            die(2, "df_test: the kernel returned DIFFERENT BYTES with DF set (it ran backward)");

    os64_printf("df_test: the kernel is unmoved by a ring-3 direction flag (%ld bytes, identical)\n",
                (long)n1);

    // ── 2. KERNEL -> A SIGNAL HANDLER ──────────────────────────────────────
    if (os64_signal_set_handler(OS64_SIGINT, on_sigint) < 0)
        die(3, "df_test: could not install the SIGINT handler");

    // Raise SIGINT on ourselves through our own /proc ctl. The handle is
    // opened with DF clear; only the WRITE that arms delivery carries the
    // flag, so the handler is entered from an interrupted context that
    // genuinely had DF set — which is the whole point.
    char path[64];
    os64_snprintf(path, sizeof(path), "/proc/%lu/ctl", (unsigned long)os64_taskid());
    int64_t ctl = os64_open(path, "w");
    if (ctl < 0)
        die(3, "df_test: could not open my own /proc ctl");

    static const char kVerb[] = "interrupt";
    uint64_t flags_after = 0;
    __asm__ volatile(
        "std\n\t"
        "syscall\n\t"            // delivery arms on THIS syscall's exit
        "pushfq\n\t"             // ...and we resume HERE, after sigreturn
        "pop %[after]\n\t"
        "cld\n\t"
        : [after] "=&r"(flags_after)
        : "a"((uint64_t)SYSCALL_WRITE), "D"((uint64_t)(uint32_t)ctl),
          "S"((uint64_t)(uintptr_t)kVerb), "d"((uint64_t)(sizeof(kVerb) - 1))
        : "rcx", "r11", "memory");
    os64_close((int32_t)ctl);

    if (gHandlerRan != OS64_SIGINT)
        die(4, "df_test: the SIGINT handler never ran");
    if (gFlagsInHandler & RFLAGS_DF)
        die(5, "df_test: the handler was entered with DF SET (SysV requires it clear)");
    if (!(flags_after & RFLAGS_DF))
        die(6, "df_test: DF was not restored after sigreturn (the frame lost a flag)");

    os64_printf("df_test: handler entered with DF clear, and DF restored on return - all correct\n");
    os64_serial_log("df_test: direction flag honoured across both ring boundaries");
    os64_exit(STEP(0));
    return 0;   // not reached
}
