# shared.mk — how libmath.so is built.
#
# libmath.so is a LEAF, like libfreetype.so: no DT_NEEDED, every symbol it
# references resolved from its own objects, and --no-undefined on the link
# turns that from an intention into a build failure. Arithmetic needs no
# allocator, no I/O and no system call, and a library that cannot reach
# one cannot grow a dependency on one by accident.
include libmath/sources.mk

LIBMATH_SO   := $(BIN)/libmath.so
LIBMATH_BASE := $(patsubst libmath.so=%,%,$(filter libmath.so=%,$(LIB_BASE_PAIRS)))
MATH_OBJS    := $(patsubst %,$(OBJ)/math/%.o,$(MATH_UPSTREAM_SRCS) $(MATH_PORT_SRCS))

# musl's bits/alltypes.h is GENERATED by its own build, from two templates
# and a sed script that are all vendored unmodified; doing the same here
# keeps every upstream byte pinned by manifest.json.
MATH_ALLTYPES := $(OBJ)/math/include/bits/alltypes.h
$(MATH_ALLTYPES): libmath/upstream/tools/mkalltypes.sed \
        libmath/upstream/arch/x86_64/bits/alltypes.h.in \
        libmath/upstream/include/alltypes.h.in
	@mkdir -p "$(dir $@)"
	sed -f $^ > $@

# THE FLAGS THAT DECIDE THE NUMBERS. Floating-point results depend on how the
# compiler is allowed to evaluate an expression, so these are part of the
# library's correctness, not its tuning:
#   -ffp-contract=off           no fused multiply-add: a*b+c rounds twice,
#                               as the source and its error analysis assume
#   -fexcess-precision=standard every double operation rounds to double
#   -fno-fast-math              signed zero, NaN and infinity are real values
#   -mno-avx -mno-fma           the SSE2 baseline, on every x86-64 os64 runs on
# -fno-builtin keeps GCC from replacing a call to floor or scalbn inside the
# library with its own idea of one, and -fno-tree-loop-distribute-patterns
# keeps it from inventing a memset the leaf link has nothing to satisfy.
#
# -nostdinc and the include ORDER are musl's own: upstream sources see the
# vendored private headers and nothing else — not the compiler's stdint.h,
# and not os64's public <math.h>, which belongs to consumers.
#
# The repository's -I list is filtered out for the same reason. Every other
# flag is userland's, including -Wall -Wextra -Werror.
MATH_FLAGS := $(filter-out -I%,$(LIBOS64_CFLAGS)) -O2 -std=c99 -nostdinc \
    -fno-builtin -fno-fast-math -ffp-contract=off -fexcess-precision=standard \
    -mno-avx -mno-fma -fno-tree-loop-distribute-patterns
MATH_UPSTREAM_INCLUDES := -Ilibmath/upstream/arch/x86_64 \
    -Ilibmath/upstream/arch/generic -I$(OBJ)/math/include \
    -Ilibmath/upstream/src/include -Ilibmath/upstream/src/internal \
    -Ilibmath/upstream/include

# UPSTREAM FILES ONLY, and each flag for a diagnosed reason
# (libmath/UPSTREAM_REVIEW.md § Warnings): -Wno-parentheses for musl's
# operator-precedence style in endian.h, which libm.h includes, and in a few
# routines' own expressions; -Wno-unused-but-set-variable for libm.h's
# force-eval helpers, whose volatile stores exist to make the CPU raise a
# floating-point flag and must not be removed. os64's own code keeps the full
# alarm.
MATH_UPSTREAM_FLAGS := $(MATH_UPSTREAM_INCLUDES) -Wno-parentheses \
    -Wno-unused-but-set-variable

# The one per-file exception. GCC cannot prove `fq` is written before the
# reduction reads it, because the proof depends on the CONTENTS of iq[]; the
# control-flow argument that it always is lives in UPSTREAM_REVIEW.md.
MATH_REM_PIO2_LARGE_FLAGS := -Wno-maybe-uninitialized
$(OBJ)/math/libmath/upstream/src/math/__rem_pio2_large.c.o: MATH_FILE_FLAGS := $(MATH_REM_PIO2_LARGE_FLAGS)

# The adapter is os64's: public header only, and -fno-math-errno, without
# which GCC's sqrt builtin keeps a call to sqrt for the negative case — a
# call that, here, would be to itself.
MATH_SQRT_FLAGS := -Ilibmath/include -fno-math-errno
$(OBJ)/math/libmath/port/sqrt.c.o: MATH_FILE_FLAGS := $(MATH_SQRT_FLAGS)

$(OBJ)/math/libmath/%.c.o: libmath/%.c libmath/shared.mk $(MATH_ALLTYPES)
	@mkdir -p "$(dir $@)"
	$(CC) $(MATH_FLAGS) $(if $(findstring /upstream/,$<),$(MATH_UPSTREAM_FLAGS)) $(MATH_FILE_FLAGS) -c $< -o $@

# No $(LIBOS64_SO) on this line, and that absence is the design (see the top).
# sources.mk IS on it: removing a routine from the list creates no newer
# object, so without it the old library — removed code and all — would look
# up to date.
$(LIBMATH_SO): $(MATH_OBJS) libmath/exports.map link/lib.ld \
        tools/app_bases.py libmath/shared.mk libmath/sources.mk
	@mkdir -p "$(BIN)"
	$(LD) --defsym LIB_BASE=$(LIBMATH_BASE) --defsym LIB_SLOT_SIZE=$(LIB_SLOT_SIZE) \
	    $(SHARED_LIB_LDFLAGS) -soname libmath.so --no-undefined --no-as-needed \
	    --version-script=libmath/exports.map -Map=$(OBJ)/math/link.map \
	    -o $@ $(MATH_OBJS)

# tools/test_math_host.sh builds the same sources on the host from THESE
# variables, so its reference and libmath.so differ in the compiler and
# nothing else. Shell assignments, for the script to eval; paths are
# relative to userland/.
.PHONY: math-host-flags
math-host-flags: $(MATH_ALLTYPES)
	@printf "MATH_FLAGS='%s'\n" "$(MATH_FLAGS)"
	@printf "MATH_UPSTREAM_FLAGS='%s'\n" "$(MATH_UPSTREAM_FLAGS)"
	@printf "MATH_REM_PIO2_LARGE_FLAGS='%s'\n" "$(MATH_REM_PIO2_LARGE_FLAGS)"
	@printf "MATH_SQRT_FLAGS='%s'\n" "$(MATH_SQRT_FLAGS)"
	@printf "MATH_UPSTREAM_SRCS='%s'\n" "$(MATH_UPSTREAM_SRCS)"
	@printf "MATH_PORT_SRCS='%s'\n" "$(MATH_PORT_SRCS)"
	@printf "MATH_PUBLIC_NAMES='%s'\n" "$(MATH_PUBLIC_NAMES) sqrt"
	@printf "MATH_OBJS='%s'\n" "$(MATH_OBJS)"

-include $(MATH_OBJS:.o=.d)
