# Production archive members required by the private client/policy profile.
# Audited against the shared link map; fixture and server code stay outside.
LIBTLS_CORE_SOURCES := \
    libtls/port/certificate_der.c \
    libtls/port/certificate_policy.c \
    libtls/port/client_engine.c \
    libtls/port/client_profile.c \
    libtls/port/runtime.c \
    libtls/upstream/src/codec/ccopy.c \
    libtls/upstream/src/codec/dec32be.c \
    libtls/upstream/src/codec/dec32le.c \
    libtls/upstream/src/codec/dec64be.c \
    libtls/upstream/src/codec/enc32be.c \
    libtls/upstream/src/codec/enc32le.c \
    libtls/upstream/src/codec/enc64be.c \
    libtls/upstream/src/ec/ec_all_m31.c \
    libtls/upstream/src/ec/ec_c25519_m31.c \
    libtls/upstream/src/ec/ec_p256_m31.c \
    libtls/upstream/src/ec/ec_prime_i31.c \
    libtls/upstream/src/ec/ec_secp256r1.c \
    libtls/upstream/src/ec/ec_secp384r1.c \
    libtls/upstream/src/ec/ec_secp521r1.c \
    libtls/upstream/src/ec/ecdsa_atr.c \
    libtls/upstream/src/ec/ecdsa_i31_bits.c \
    libtls/upstream/src/ec/ecdsa_i31_vrfy_asn1.c \
    libtls/upstream/src/ec/ecdsa_i31_vrfy_raw.c \
    libtls/upstream/src/hash/ghash_ctmul64.c \
    libtls/upstream/src/hash/multihash.c \
    libtls/upstream/src/hash/sha2big.c \
    libtls/upstream/src/hash/sha2small.c \
    libtls/upstream/src/int/i31_add.c \
    libtls/upstream/src/int/i31_bitlen.c \
    libtls/upstream/src/int/i31_decmod.c \
    libtls/upstream/src/int/i31_decode.c \
    libtls/upstream/src/int/i31_encode.c \
    libtls/upstream/src/int/i31_fmont.c \
    libtls/upstream/src/int/i31_iszero.c \
    libtls/upstream/src/int/i31_modpow.c \
    libtls/upstream/src/int/i31_modpow2.c \
    libtls/upstream/src/int/i31_montmul.c \
    libtls/upstream/src/int/i31_muladd.c \
    libtls/upstream/src/int/i31_ninv31.c \
    libtls/upstream/src/int/i31_rshift.c \
    libtls/upstream/src/int/i31_sub.c \
    libtls/upstream/src/int/i31_tmont.c \
    libtls/upstream/src/int/i32_div32.c \
    libtls/upstream/src/mac/hmac.c \
    libtls/upstream/src/rand/hmac_drbg.c \
    libtls/upstream/src/rand/sysrng.c \
    libtls/upstream/src/rsa/rsa_i31_pkcs1_vrfy.c \
    libtls/upstream/src/rsa/rsa_i31_pub.c \
    libtls/upstream/src/rsa/rsa_pkcs1_sig_unpad.c \
    libtls/upstream/src/ssl/prf.c \
    libtls/upstream/src/ssl/prf_sha256.c \
    libtls/upstream/src/ssl/prf_sha384.c \
    libtls/upstream/src/ssl/ssl_client.c \
    libtls/upstream/src/ssl/ssl_engine.c \
    libtls/upstream/src/ssl/ssl_hs_client.c \
    libtls/upstream/src/ssl/ssl_rec_chapol.c \
    libtls/upstream/src/ssl/ssl_rec_gcm.c \
    libtls/upstream/src/symcipher/aes_ct64.c \
    libtls/upstream/src/symcipher/aes_ct64_ctr.c \
    libtls/upstream/src/symcipher/aes_ct64_enc.c \
    libtls/upstream/src/symcipher/chacha20_ct.c \
    libtls/upstream/src/symcipher/poly1305_ctmul.c \
    libtls/upstream/src/x509/x509_minimal.c
