# Complete core for the foundation archive and reference tests.
# The public TLS client link profile is a separate slice.
BEARSSL_SOURCES := \
  libtls/upstream/src/aead/ccm.c \
  libtls/upstream/src/aead/eax.c \
  libtls/upstream/src/aead/gcm.c \
  libtls/upstream/src/codec/ccopy.c \
  libtls/upstream/src/codec/dec16be.c \
  libtls/upstream/src/codec/dec16le.c \
  libtls/upstream/src/codec/dec32be.c \
  libtls/upstream/src/codec/dec32le.c \
  libtls/upstream/src/codec/dec64be.c \
  libtls/upstream/src/codec/dec64le.c \
  libtls/upstream/src/codec/enc16be.c \
  libtls/upstream/src/codec/enc16le.c \
  libtls/upstream/src/codec/enc32be.c \
  libtls/upstream/src/codec/enc32le.c \
  libtls/upstream/src/codec/enc64be.c \
  libtls/upstream/src/codec/enc64le.c \
  libtls/upstream/src/codec/pemdec.c \
  libtls/upstream/src/codec/pemenc.c \
  libtls/upstream/src/ec/ec_all_m15.c \
  libtls/upstream/src/ec/ec_all_m31.c \
  libtls/upstream/src/ec/ec_c25519_i15.c \
  libtls/upstream/src/ec/ec_c25519_i31.c \
  libtls/upstream/src/ec/ec_c25519_m15.c \
  libtls/upstream/src/ec/ec_c25519_m31.c \
  libtls/upstream/src/ec/ec_c25519_m62.c \
  libtls/upstream/src/ec/ec_c25519_m64.c \
  libtls/upstream/src/ec/ec_curve25519.c \
  libtls/upstream/src/ec/ec_default.c \
  libtls/upstream/src/ec/ec_keygen.c \
  libtls/upstream/src/ec/ec_p256_m15.c \
  libtls/upstream/src/ec/ec_p256_m31.c \
  libtls/upstream/src/ec/ec_p256_m62.c \
  libtls/upstream/src/ec/ec_p256_m64.c \
  libtls/upstream/src/ec/ec_prime_i15.c \
  libtls/upstream/src/ec/ec_prime_i31.c \
  libtls/upstream/src/ec/ec_pubkey.c \
  libtls/upstream/src/ec/ec_secp256r1.c \
  libtls/upstream/src/ec/ec_secp384r1.c \
  libtls/upstream/src/ec/ec_secp521r1.c \
  libtls/upstream/src/ec/ecdsa_atr.c \
  libtls/upstream/src/ec/ecdsa_default_sign_asn1.c \
  libtls/upstream/src/ec/ecdsa_default_sign_raw.c \
  libtls/upstream/src/ec/ecdsa_default_vrfy_asn1.c \
  libtls/upstream/src/ec/ecdsa_default_vrfy_raw.c \
  libtls/upstream/src/ec/ecdsa_i15_bits.c \
  libtls/upstream/src/ec/ecdsa_i15_sign_asn1.c \
  libtls/upstream/src/ec/ecdsa_i15_sign_raw.c \
  libtls/upstream/src/ec/ecdsa_i15_vrfy_asn1.c \
  libtls/upstream/src/ec/ecdsa_i15_vrfy_raw.c \
  libtls/upstream/src/ec/ecdsa_i31_bits.c \
  libtls/upstream/src/ec/ecdsa_i31_sign_asn1.c \
  libtls/upstream/src/ec/ecdsa_i31_sign_raw.c \
  libtls/upstream/src/ec/ecdsa_i31_vrfy_asn1.c \
  libtls/upstream/src/ec/ecdsa_i31_vrfy_raw.c \
  libtls/upstream/src/ec/ecdsa_rta.c \
  libtls/upstream/src/hash/dig_oid.c \
  libtls/upstream/src/hash/dig_size.c \
  libtls/upstream/src/hash/ghash_ctmul.c \
  libtls/upstream/src/hash/ghash_ctmul32.c \
  libtls/upstream/src/hash/ghash_ctmul64.c \
  libtls/upstream/src/hash/ghash_pclmul.c \
  libtls/upstream/src/hash/ghash_pwr8.c \
  libtls/upstream/src/hash/md5.c \
  libtls/upstream/src/hash/md5sha1.c \
  libtls/upstream/src/hash/mgf1.c \
  libtls/upstream/src/hash/multihash.c \
  libtls/upstream/src/hash/sha1.c \
  libtls/upstream/src/hash/sha2big.c \
  libtls/upstream/src/hash/sha2small.c \
  libtls/upstream/src/int/i15_add.c \
  libtls/upstream/src/int/i15_bitlen.c \
  libtls/upstream/src/int/i15_decmod.c \
  libtls/upstream/src/int/i15_decode.c \
  libtls/upstream/src/int/i15_decred.c \
  libtls/upstream/src/int/i15_encode.c \
  libtls/upstream/src/int/i15_fmont.c \
  libtls/upstream/src/int/i15_iszero.c \
  libtls/upstream/src/int/i15_moddiv.c \
  libtls/upstream/src/int/i15_modpow.c \
  libtls/upstream/src/int/i15_modpow2.c \
  libtls/upstream/src/int/i15_montmul.c \
  libtls/upstream/src/int/i15_mulacc.c \
  libtls/upstream/src/int/i15_muladd.c \
  libtls/upstream/src/int/i15_ninv15.c \
  libtls/upstream/src/int/i15_reduce.c \
  libtls/upstream/src/int/i15_rshift.c \
  libtls/upstream/src/int/i15_sub.c \
  libtls/upstream/src/int/i15_tmont.c \
  libtls/upstream/src/int/i31_add.c \
  libtls/upstream/src/int/i31_bitlen.c \
  libtls/upstream/src/int/i31_decmod.c \
  libtls/upstream/src/int/i31_decode.c \
  libtls/upstream/src/int/i31_decred.c \
  libtls/upstream/src/int/i31_encode.c \
  libtls/upstream/src/int/i31_fmont.c \
  libtls/upstream/src/int/i31_iszero.c \
  libtls/upstream/src/int/i31_moddiv.c \
  libtls/upstream/src/int/i31_modpow.c \
  libtls/upstream/src/int/i31_modpow2.c \
  libtls/upstream/src/int/i31_montmul.c \
  libtls/upstream/src/int/i31_mulacc.c \
  libtls/upstream/src/int/i31_muladd.c \
  libtls/upstream/src/int/i31_ninv31.c \
  libtls/upstream/src/int/i31_reduce.c \
  libtls/upstream/src/int/i31_rshift.c \
  libtls/upstream/src/int/i31_sub.c \
  libtls/upstream/src/int/i31_tmont.c \
  libtls/upstream/src/int/i32_add.c \
  libtls/upstream/src/int/i32_bitlen.c \
  libtls/upstream/src/int/i32_decmod.c \
  libtls/upstream/src/int/i32_decode.c \
  libtls/upstream/src/int/i32_decred.c \
  libtls/upstream/src/int/i32_div32.c \
  libtls/upstream/src/int/i32_encode.c \
  libtls/upstream/src/int/i32_fmont.c \
  libtls/upstream/src/int/i32_iszero.c \
  libtls/upstream/src/int/i32_modpow.c \
  libtls/upstream/src/int/i32_montmul.c \
  libtls/upstream/src/int/i32_mulacc.c \
  libtls/upstream/src/int/i32_muladd.c \
  libtls/upstream/src/int/i32_ninv32.c \
  libtls/upstream/src/int/i32_reduce.c \
  libtls/upstream/src/int/i32_sub.c \
  libtls/upstream/src/int/i32_tmont.c \
  libtls/upstream/src/int/i62_modpow2.c \
  libtls/upstream/src/kdf/hkdf.c \
  libtls/upstream/src/kdf/shake.c \
  libtls/upstream/src/mac/hmac.c \
  libtls/upstream/src/mac/hmac_ct.c \
  libtls/upstream/src/rand/aesctr_drbg.c \
  libtls/upstream/src/rand/hmac_drbg.c \
  libtls/upstream/src/rand/sysrng.c \
  libtls/upstream/src/rsa/rsa_default_keygen.c \
  libtls/upstream/src/rsa/rsa_default_modulus.c \
  libtls/upstream/src/rsa/rsa_default_oaep_decrypt.c \
  libtls/upstream/src/rsa/rsa_default_oaep_encrypt.c \
  libtls/upstream/src/rsa/rsa_default_pkcs1_sign.c \
  libtls/upstream/src/rsa/rsa_default_pkcs1_vrfy.c \
  libtls/upstream/src/rsa/rsa_default_priv.c \
  libtls/upstream/src/rsa/rsa_default_privexp.c \
  libtls/upstream/src/rsa/rsa_default_pss_sign.c \
  libtls/upstream/src/rsa/rsa_default_pss_vrfy.c \
  libtls/upstream/src/rsa/rsa_default_pub.c \
  libtls/upstream/src/rsa/rsa_default_pubexp.c \
  libtls/upstream/src/rsa/rsa_i15_keygen.c \
  libtls/upstream/src/rsa/rsa_i15_modulus.c \
  libtls/upstream/src/rsa/rsa_i15_oaep_decrypt.c \
  libtls/upstream/src/rsa/rsa_i15_oaep_encrypt.c \
  libtls/upstream/src/rsa/rsa_i15_pkcs1_sign.c \
  libtls/upstream/src/rsa/rsa_i15_pkcs1_vrfy.c \
  libtls/upstream/src/rsa/rsa_i15_priv.c \
  libtls/upstream/src/rsa/rsa_i15_privexp.c \
  libtls/upstream/src/rsa/rsa_i15_pss_sign.c \
  libtls/upstream/src/rsa/rsa_i15_pss_vrfy.c \
  libtls/upstream/src/rsa/rsa_i15_pub.c \
  libtls/upstream/src/rsa/rsa_i15_pubexp.c \
  libtls/upstream/src/rsa/rsa_i31_keygen.c \
  libtls/upstream/src/rsa/rsa_i31_keygen_inner.c \
  libtls/upstream/src/rsa/rsa_i31_modulus.c \
  libtls/upstream/src/rsa/rsa_i31_oaep_decrypt.c \
  libtls/upstream/src/rsa/rsa_i31_oaep_encrypt.c \
  libtls/upstream/src/rsa/rsa_i31_pkcs1_sign.c \
  libtls/upstream/src/rsa/rsa_i31_pkcs1_vrfy.c \
  libtls/upstream/src/rsa/rsa_i31_priv.c \
  libtls/upstream/src/rsa/rsa_i31_privexp.c \
  libtls/upstream/src/rsa/rsa_i31_pss_sign.c \
  libtls/upstream/src/rsa/rsa_i31_pss_vrfy.c \
  libtls/upstream/src/rsa/rsa_i31_pub.c \
  libtls/upstream/src/rsa/rsa_i31_pubexp.c \
  libtls/upstream/src/rsa/rsa_i32_oaep_decrypt.c \
  libtls/upstream/src/rsa/rsa_i32_oaep_encrypt.c \
  libtls/upstream/src/rsa/rsa_i32_pkcs1_sign.c \
  libtls/upstream/src/rsa/rsa_i32_pkcs1_vrfy.c \
  libtls/upstream/src/rsa/rsa_i32_priv.c \
  libtls/upstream/src/rsa/rsa_i32_pss_sign.c \
  libtls/upstream/src/rsa/rsa_i32_pss_vrfy.c \
  libtls/upstream/src/rsa/rsa_i32_pub.c \
  libtls/upstream/src/rsa/rsa_i62_keygen.c \
  libtls/upstream/src/rsa/rsa_i62_oaep_decrypt.c \
  libtls/upstream/src/rsa/rsa_i62_oaep_encrypt.c \
  libtls/upstream/src/rsa/rsa_i62_pkcs1_sign.c \
  libtls/upstream/src/rsa/rsa_i62_pkcs1_vrfy.c \
  libtls/upstream/src/rsa/rsa_i62_priv.c \
  libtls/upstream/src/rsa/rsa_i62_pss_sign.c \
  libtls/upstream/src/rsa/rsa_i62_pss_vrfy.c \
  libtls/upstream/src/rsa/rsa_i62_pub.c \
  libtls/upstream/src/rsa/rsa_oaep_pad.c \
  libtls/upstream/src/rsa/rsa_oaep_unpad.c \
  libtls/upstream/src/rsa/rsa_pkcs1_sig_pad.c \
  libtls/upstream/src/rsa/rsa_pkcs1_sig_unpad.c \
  libtls/upstream/src/rsa/rsa_pss_sig_pad.c \
  libtls/upstream/src/rsa/rsa_pss_sig_unpad.c \
  libtls/upstream/src/rsa/rsa_ssl_decrypt.c \
  libtls/upstream/src/settings.c \
  libtls/upstream/src/ssl/prf.c \
  libtls/upstream/src/ssl/prf_md5sha1.c \
  libtls/upstream/src/ssl/prf_sha256.c \
  libtls/upstream/src/ssl/prf_sha384.c \
  libtls/upstream/src/ssl/ssl_ccert_single_ec.c \
  libtls/upstream/src/ssl/ssl_ccert_single_rsa.c \
  libtls/upstream/src/ssl/ssl_client.c \
  libtls/upstream/src/ssl/ssl_client_default_rsapub.c \
  libtls/upstream/src/ssl/ssl_client_full.c \
  libtls/upstream/src/ssl/ssl_engine.c \
  libtls/upstream/src/ssl/ssl_engine_default_aescbc.c \
  libtls/upstream/src/ssl/ssl_engine_default_aesccm.c \
  libtls/upstream/src/ssl/ssl_engine_default_aesgcm.c \
  libtls/upstream/src/ssl/ssl_engine_default_chapol.c \
  libtls/upstream/src/ssl/ssl_engine_default_descbc.c \
  libtls/upstream/src/ssl/ssl_engine_default_ec.c \
  libtls/upstream/src/ssl/ssl_engine_default_ecdsa.c \
  libtls/upstream/src/ssl/ssl_engine_default_rsavrfy.c \
  libtls/upstream/src/ssl/ssl_hashes.c \
  libtls/upstream/src/ssl/ssl_hs_client.c \
  libtls/upstream/src/ssl/ssl_hs_server.c \
  libtls/upstream/src/ssl/ssl_io.c \
  libtls/upstream/src/ssl/ssl_keyexport.c \
  libtls/upstream/src/ssl/ssl_lru.c \
  libtls/upstream/src/ssl/ssl_rec_cbc.c \
  libtls/upstream/src/ssl/ssl_rec_ccm.c \
  libtls/upstream/src/ssl/ssl_rec_chapol.c \
  libtls/upstream/src/ssl/ssl_rec_gcm.c \
  libtls/upstream/src/ssl/ssl_scert_single_ec.c \
  libtls/upstream/src/ssl/ssl_scert_single_rsa.c \
  libtls/upstream/src/ssl/ssl_server.c \
  libtls/upstream/src/ssl/ssl_server_full_ec.c \
  libtls/upstream/src/ssl/ssl_server_full_rsa.c \
  libtls/upstream/src/ssl/ssl_server_mine2c.c \
  libtls/upstream/src/ssl/ssl_server_mine2g.c \
  libtls/upstream/src/ssl/ssl_server_minf2c.c \
  libtls/upstream/src/ssl/ssl_server_minf2g.c \
  libtls/upstream/src/ssl/ssl_server_minr2g.c \
  libtls/upstream/src/ssl/ssl_server_minu2g.c \
  libtls/upstream/src/ssl/ssl_server_minv2g.c \
  libtls/upstream/src/symcipher/aes_big_cbcdec.c \
  libtls/upstream/src/symcipher/aes_big_cbcenc.c \
  libtls/upstream/src/symcipher/aes_big_ctr.c \
  libtls/upstream/src/symcipher/aes_big_ctrcbc.c \
  libtls/upstream/src/symcipher/aes_big_dec.c \
  libtls/upstream/src/symcipher/aes_big_enc.c \
  libtls/upstream/src/symcipher/aes_common.c \
  libtls/upstream/src/symcipher/aes_ct.c \
  libtls/upstream/src/symcipher/aes_ct64.c \
  libtls/upstream/src/symcipher/aes_ct64_cbcdec.c \
  libtls/upstream/src/symcipher/aes_ct64_cbcenc.c \
  libtls/upstream/src/symcipher/aes_ct64_ctr.c \
  libtls/upstream/src/symcipher/aes_ct64_ctrcbc.c \
  libtls/upstream/src/symcipher/aes_ct64_dec.c \
  libtls/upstream/src/symcipher/aes_ct64_enc.c \
  libtls/upstream/src/symcipher/aes_ct_cbcdec.c \
  libtls/upstream/src/symcipher/aes_ct_cbcenc.c \
  libtls/upstream/src/symcipher/aes_ct_ctr.c \
  libtls/upstream/src/symcipher/aes_ct_ctrcbc.c \
  libtls/upstream/src/symcipher/aes_ct_dec.c \
  libtls/upstream/src/symcipher/aes_ct_enc.c \
  libtls/upstream/src/symcipher/aes_pwr8.c \
  libtls/upstream/src/symcipher/aes_pwr8_cbcdec.c \
  libtls/upstream/src/symcipher/aes_pwr8_cbcenc.c \
  libtls/upstream/src/symcipher/aes_pwr8_ctr.c \
  libtls/upstream/src/symcipher/aes_pwr8_ctrcbc.c \
  libtls/upstream/src/symcipher/aes_small_cbcdec.c \
  libtls/upstream/src/symcipher/aes_small_cbcenc.c \
  libtls/upstream/src/symcipher/aes_small_ctr.c \
  libtls/upstream/src/symcipher/aes_small_ctrcbc.c \
  libtls/upstream/src/symcipher/aes_small_dec.c \
  libtls/upstream/src/symcipher/aes_small_enc.c \
  libtls/upstream/src/symcipher/aes_x86ni.c \
  libtls/upstream/src/symcipher/aes_x86ni_cbcdec.c \
  libtls/upstream/src/symcipher/aes_x86ni_cbcenc.c \
  libtls/upstream/src/symcipher/aes_x86ni_ctr.c \
  libtls/upstream/src/symcipher/aes_x86ni_ctrcbc.c \
  libtls/upstream/src/symcipher/chacha20_ct.c \
  libtls/upstream/src/symcipher/chacha20_sse2.c \
  libtls/upstream/src/symcipher/des_ct.c \
  libtls/upstream/src/symcipher/des_ct_cbcdec.c \
  libtls/upstream/src/symcipher/des_ct_cbcenc.c \
  libtls/upstream/src/symcipher/des_support.c \
  libtls/upstream/src/symcipher/des_tab.c \
  libtls/upstream/src/symcipher/des_tab_cbcdec.c \
  libtls/upstream/src/symcipher/des_tab_cbcenc.c \
  libtls/upstream/src/symcipher/poly1305_ctmul.c \
  libtls/upstream/src/symcipher/poly1305_ctmul32.c \
  libtls/upstream/src/symcipher/poly1305_ctmulq.c \
  libtls/upstream/src/symcipher/poly1305_i15.c \
  libtls/upstream/src/x509/asn1enc.c \
  libtls/upstream/src/x509/encode_ec_pk8der.c \
  libtls/upstream/src/x509/encode_ec_rawder.c \
  libtls/upstream/src/x509/encode_rsa_pk8der.c \
  libtls/upstream/src/x509/encode_rsa_rawder.c \
  libtls/upstream/src/x509/skey_decoder.c \
  libtls/upstream/src/x509/x509_decoder.c \
  libtls/upstream/src/x509/x509_knownkey.c \
  libtls/upstream/src/x509/x509_minimal.c \
  libtls/upstream/src/x509/x509_minimal_full.c
