#!/usr/bin/env python3
"""Extract attributed upstream vectors and a binary-distribution license notice."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
base = root / "userland/libtls"
source = (base / "upstream/test/test_crypto.c").read_text()
license_text = (base / "upstream/LICENSE.txt").read_text()
pieces = [source[:source.index("#include")],
          "// Generated by tools/bearssl_vectors.py; edit the generator.\n"]
for start, end in [
    ("static const char *const KAT_GCM[]", "static void\ntest_GCM"),
    ("static const unsigned char EC_P256_PUB_POINT[]", "static void\ntest_ECDSA_KAT"),
]:
    pieces.append(source[source.index(start):source.index(end)])
pieces.append("static const char bearssl_license[] =\n" +
              "\n".join(json.dumps(line + "\n") for line in license_text.splitlines()) + ";\n")
cert = (base / "upstream/test/x509/ee-p256.crt").read_bytes()
pieces.append("static const unsigned char time_test_certificate[] = {\n" +
              "\n".join("    " + ", ".join(f"0x{b:02x}" for b in cert[i:i+12]) + ","
                        for i in range(0, len(cert), 12)) + "\n};\n")
output = "\n".join(pieces)
target = base / "test/vectors.h"
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
if args.check:
    if target.read_text() != output:
        raise SystemExit("BearSSL vector header differs: run tools/bearssl_vectors.py")
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(output)
