#!/usr/bin/env python3
"""Generate HTML tag and entity tables from checked-in inputs."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / 'userland/libhtml'
ap = argparse.ArgumentParser(description=__doc__)
ap.add_argument('--check', action='store_true')
args = ap.parse_args()
def emit(path, text):
    if args.check:
        if path.read_bytes() != text.encode():
            raise SystemExit(f'{path}: generated table is stale')
    else:
        path.write_text(text)
names = (LIB / 'tags.txt').read_text().split()
emit(LIB / 'include/html/tags.h',
    '/* Generated by tools/gen_html_tables.py; edit tags.txt. */\n'
    '#ifndef OS64_HTML_TAGS_H\n#define OS64_HTML_TAGS_H\n'
    'typedef enum {\n    OS64_HTML_TAG_UNKNOWN,\n' +
    ''.join('    OS64_HTML_TAG_' + n.upper() + ',\n' for n in names) +
    '    OS64_HTML_TAG_COUNT\n} os64_html_tag_t;\n#endif\n')
emit(LIB / 'tags.inc', '/* Generated from tags.txt. */\n' +
    ',\n'.join('"' + n + '"' for n in [''] + names) + '\n')
entities = json.loads((ROOT / 'tools/html5lib-tests/standard/entities.json').read_text())
emit(LIB / 'entities.inc',
    '/* Generated from the pinned WHATWG entities.json; do not edit. */\n' +
    ''.join('{"%s", %d, %d},\n' % (k[1:], v['codepoints'][0],
                                     (v['codepoints'] + [0])[1])
            for k, v in sorted(entities.items())))
print(len(names), 'tags;', len(entities), 'entities')

# Adjustment and quirks tables are extracted from the pinned standard source.
import re
source=re.sub(r'<!--.*?-->', '', (ROOT/'tools/html5lib-tests/standard/source').read_text(), flags=re.S)
for name,needle in [('svg_tags','<code data-x="">altglyph</code>'),('svg_attrs','<code data-x="">attributename</code>')]:
    start=source.index(needle);start=source.rfind('<tr>',0,start)
    end=source.index('</table>',start)
    pairs=re.findall(r'<tr>\s*<td> <code data-x="">([^<]+)</code>\s*<td> <code data-x="">([^<]+)</code>',source[start:end])
    emit(LIB/(name+'.inc'), '/* Generated from the pinned HTML Standard. */\n'+''.join('{"%s", "%s"},\n'%pair for pair in pairs))
start=source.index('id="quirks-mode-doctypes"');end=source.index('</ul>',start)
prefixes=re.findall(r'The public identifier starts with: "<code data-x="">([^<]+)</code>',source[start:end])
emit(LIB/'quirks.inc', '/* Generated from the pinned HTML Standard. */\n'+''.join(json.dumps(x.lower())+',\n' for x in prefixes))
