#!/usr/bin/env python3
"""Independent Decimal oracle for the fixed browser range observations.

800 digits cover the full finite binary64 exponent span. Results are compared
as numbers: a browser may rewrite an unchanged value's spelling. The table
retains browser observations separately, including precision-edge differences.
"""
import argparse
import decimal
import json
import math
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent

def number(text, strict=False):
    if text is None:
        return None
    if strict and not re.fullmatch(r'-?(?:[0-9]+(?:\.[0-9]+)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?', text):
        return None
    m = re.match(r'^[\t\n\f\r ]*[+-]?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?', text)
    if not m:
        return None
    value = float(m[0])
    return decimal.Decimal(str(value)) if math.isfinite(value) else None

def expected(attrs):
    fields = dict((m[0], m[1] or m[2]) for m in
                  re.findall(r'(min|max|step|value)=(?:"([^"]*)"|([^ ]+))', attrs))
    low, high = number(fields.get('min')), number(fields.get('max'))
    base = low if low is not None else number(fields.get('value'))
    if low is None: low = decimal.Decimal(0)
    if high is None: high = decimal.Decimal(100)
    if base is None: base = decimal.Decimal(0)
    value = number(fields.get('value'), strict=True)
    if high < low:
        return str(float(low))
    if value is None: value = (low+high)/2
    value = min(high,max(low,value))
    if fields.get('step','').lower() != 'any':
        step = number(fields.get('step'))
        if step is None or step <= 0: step = decimal.Decimal(1)
        q = ((value-base)/step).to_integral_value(rounding=decimal.ROUND_FLOOR)
        below = base+q*step
        above = below+step
        candidates = [c for c in (below,above) if low <= c <= high]
        if candidates: value = min(candidates,key=lambda c:(abs(c-value),-c))
    return str(float(value))

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    source=json.loads((ROOT/'libpage_range_reference.json').read_text())
    out=['// Generated by gen_libpage_range.py; browser observations are retained in JSON.',
         '// Expected numeric values come from independent 800-digit Decimal arithmetic.',
         'static const struct {const char *html, *value;} range_reference[] = {']
    divergences=0
    with decimal.localcontext() as ctx:
        ctx.prec=800
        for attrs,observed in source['cases']:
            want=expected(attrs)
            if float(want) != float(observed): divergences+=1
            out.append('    {'+json.dumps('<input type=range '+attrs+'>')+', '+json.dumps(want)+'},')
    out.append('};')
    output='\n'.join(out)+'\n'
    target=ROOT/'test_libpage_range.inc'
    if args.check:
        if target.read_text()!=output: raise SystemExit('range fixtures are stale')
    else: target.write_text(output)
    print(f'range oracle: {len(source["cases"])} cases; {divergences} browser precision-edge differences retained')
if __name__=='__main__': main()
