#!/usr/bin/env python3
"""Generate libos64's Bidi_Class range table from the pinned Unicode data.

The table answers one question — which STRONG bidirectional class a code
point has, if any — because that is what decides a run's direction: UAX #9's
P2/P3 take the first character of type L, R or AL and ignore everything else.
HTML's `dir=auto` and its `dirname` submission entry are defined in terms of
it, and a layout engine that ever draws Hebrew or Arabic needs the same
answer.

WHAT IS EMITTED IS THE EXCEPTIONS. DerivedBidiClass.txt's own default is
`@missing: 0000..10FFFF; Left_To_Right`, so everything not listed is L and
the table holds only the ranges that are NOT: R, AL, and the classes that
are not strong at all. That is a fraction of what a complete map would take,
and it keeps the file's default rule as the code's default rule rather than
as a second thing to maintain. The count is printed on every run.

    tools/gen_bidi_table.py            regenerate the .inc
    tools/gen_bidi_table.py --check    fail if the checked-in .inc is stale
    tools/gen_bidi_table.py --fetch    re-download the pinned data and verify
"""
import argparse
import hashlib
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'tools/unicode'
OUT = ROOT / 'userland/libos64/bidi_ranges.inc'

# The long names DerivedBidiClass.txt spells its @missing lines with. Only the
# three strong classes need translating; every other name falls through to
# "not strong", which is the whole of what this table records about them.
STRONG = {'Left_To_Right': 'L', 'Right_To_Left': 'R', 'Arabic_Letter': 'AL'}
# The strong classes, and what each is spelled as in the emitted table. 'L' is
# in here for the PARSE and not for the emit: an explicit Left_To_Right row has
# to record L, because a row that recorded "not strong" instead would let a
# later character decide a direction this one already settled. The emitted
# table never spells L, since L is what absence means.
CLASS = {'L': 'OS64_BIDI_L', 'R': 'OS64_BIDI_R', 'AL': 'OS64_BIDI_AL'}
LAST = 0x10FFFF


def parse(text):
    """Every code point's strong class: L, R, AL, or None for not strong."""
    # @missing lines are the per-block defaults for code points that are not
    # listed — unassigned ones inside a right-to-left block are R or AL, which
    # is why they cannot be skipped as comments. Explicit rows override them,
    # so they are applied first and in file order.
    missing, rows = [], []
    for line in text.splitlines():
        at = re.match(r'^#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+);\s*(\S+)', line)
        if at:
            missing.append((int(at.group(1), 16), int(at.group(2), 16),
                            STRONG.get(at.group(3))))
            continue
        body = line.split('#')[0].strip()
        if not body:
            continue
        span, _, name = body.partition(';')
        name = name.strip()
        first, _, last = span.strip().partition('..')
        rows.append((int(first, 16), int(last or first, 16),
                     name if name in CLASS else None))
    klass = [None] * (LAST + 1)
    for first, last, name in missing + rows:
        for cp in range(first, last + 1):
            klass[cp] = name
    return klass


def ranges(klass):
    """Merge into the ranges that are NOT L, which is the file's default."""
    out, cp = [], 0
    while cp <= LAST:
        end = cp
        while end + 1 <= LAST and klass[end + 1] == klass[cp]:
            end += 1
        if klass[cp] != 'L':
            out.append((cp, end, klass[cp]))
        cp = end + 1
    return out


def emit(pinned, table):
    version = pinned['version']
    return (f'/* Generated by tools/gen_bidi_table.py from the pinned Unicode {version}\n'
            ' * DerivedBidiClass.txt; do not edit. Ranges whose Bidi_Class is NOT\n'
            ' * Left_To_Right; anything absent is OS64_BIDI_L, which is that file\'s own\n'
            ' * default for a code point it does not list. */\n'
            + ''.join('{0x%06X, 0x%06X, %s},\n'
                      % (first, last, CLASS.get(name, 'OS64_BIDI_NOT_STRONG'))
                      for first, last, name in table))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--fetch', action='store_true',
                    help='re-download the pinned file and verify its digest')
    args = ap.parse_args()
    pinned = json.loads((DATA / 'PINNED.json').read_text())
    source = DATA / 'DerivedBidiClass.txt'
    if args.fetch:
        url = pinned['url']
        with urllib.request.urlopen(url, timeout=90) as response:
            raw = response.read()
        digest = hashlib.sha256(raw).hexdigest()
        if digest != pinned['sha256']:
            # An upstream change is a decision, not an accident: a new Unicode
            # version moves character classes and wants reading, so it takes an
            # explicit new digest in PINNED.json.
            raise SystemExit(f'{url}: digest {digest}, pinned {pinned["sha256"]}')
        source.write_bytes(raw)
        print(f'{source.name}: {len(raw)} bytes at Unicode {pinned["version"]}')
    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != pinned['sha256']:
        raise SystemExit(f'{source}: digest {digest}, pinned {pinned["sha256"]}')
    table = ranges(parse(raw.decode('utf-8')))
    text = emit(pinned, table)
    if args.check:
        if OUT.read_bytes() != text.encode():
            raise SystemExit(f'{OUT}: generated table is stale')
    else:
        OUT.write_text(text)
    strong = sum(1 for _, _, name in table if name in ('R', 'AL'))
    print(f'{len(table)} non-L ranges; {strong} right-to-left')


main()
