#!/usr/bin/env python3
"""Generate public test-only roots and leaves; scalar keys 1, 2, 3 are fixtures."""
import datetime as dt
from pathlib import Path
from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import NameOID, ExtendedKeyUsageOID

BASE = Path(__file__).resolve().parents[1] / "userland/libtls/test"


def certificate(key, name, issuer, signer, ca, serial):
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, name)])
    builder = (x509.CertificateBuilder().subject_name(name).issuer_name(issuer or name)
        .public_key(key.public_key()).serial_number(serial)
        .not_valid_before(dt.datetime(2020, 1, 1)).not_valid_after(dt.datetime(2040, 1, 1))
        .add_extension(x509.BasicConstraints(ca, None), True)
        .add_extension(x509.KeyUsage(not ca, False, False, False, False, ca, ca, None, None), True))
    if not ca:
        builder = (builder.add_extension(x509.SubjectAlternativeName([x509.DNSName("example.test")]), False)
            .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]), False))
    return builder.sign(signer, hashes.SHA256())


def main():
    header = ['#ifndef OS64_TLS_TRUST_VECTORS_H', '#define OS64_TLS_TRUST_VECTORS_H', '#include <stddef.h>']
    source = ['// Generated by tools/generate_tls_trust_fixtures.py. Public test fixtures.',
              '// Keys are deliberately trivial and confer no production trust.', '#include "trust_vectors.h"']
    leaf_key = ec.derive_private_key(3, ec.SECP256R1())
    for i, suffix in enumerate(('a', 'b'), 1):
        key = ec.derive_private_key(i, ec.SECP256R1())
        root = certificate(key, 'os64 fixture root ' + suffix, None, key, True, i)
        leaf = certificate(leaf_key, 'example.test', root.subject, key, False, i + 10)
        name = f'tls_fixture_{suffix}_pem'
        header += [f'extern const char {name}[];', f'extern const size_t {name}_length;']
        pem = root.public_bytes(serialization.Encoding.PEM).decode()
        source += [f'const char {name}[] ='] + ['    "' + line + '\\n"' for line in pem.splitlines()] + ['    ;', f'const size_t {name}_length = sizeof {name} - 1;']
        name = f'tls_fixture_{suffix}_leaf'
        data = leaf.public_bytes(serialization.Encoding.DER)
        header += [f'extern const unsigned char {name}[];', f'extern const size_t {name}_length;']
        source += [f'const unsigned char {name}[] = {{'] + ['    ' + ','.join(f'0x{x:02x}' for x in data[at:at + 16]) + ',' for at in range(0, len(data), 16)] + ['};', f'const size_t {name}_length = sizeof {name};']
    header += ['#endif']
    (BASE / 'trust_vectors.h').write_text('\n'.join(header) + '\n')
    (BASE / 'trust_vectors.c').write_text('\n'.join(source) + '\n')


if __name__ == '__main__':
    main()
