#!/usr/bin/env python3
"""test_random_host.py — emit the reference vectors tools/test_random_host.c
checks the kernel's BLAKE2s and ChaCha20 against, as a C header.

BLAKE2s comes from Python's hashlib (a native, independent implementation):
a table of messages of many lengths, unkeyed and keyed, at digest sizes 32
and 16. ChaCha20 comes from a pure-Python transcription of RFC 8439 §2.3
written here, anchored on the RFC's own §2.3.2 block vector so a slip in the
transcription fails loudly rather than agreeing with a matching slip in C.
Usage: test_random_host.py OUT_HEADER
"""
import hashlib
import random
import struct
import sys


def chacha_qr(x, a, b, c, d):
    x[a] = (x[a] + x[b]) & 0xFFFFFFFF; x[d] ^= x[a]; x[d] = ((x[d] << 16) | (x[d] >> 16)) & 0xFFFFFFFF
    x[c] = (x[c] + x[d]) & 0xFFFFFFFF; x[b] ^= x[c]; x[b] = ((x[b] << 12) | (x[b] >> 20)) & 0xFFFFFFFF
    x[a] = (x[a] + x[b]) & 0xFFFFFFFF; x[d] ^= x[a]; x[d] = ((x[d] << 8) | (x[d] >> 24)) & 0xFFFFFFFF
    x[c] = (x[c] + x[d]) & 0xFFFFFFFF; x[b] ^= x[c]; x[b] = ((x[b] << 7) | (x[b] >> 25)) & 0xFFFFFFFF


def chacha_block(key, counter, nonce):
    s = [0x61707865, 0x3320646E, 0x79622D32, 0x6B206574]
    s += list(struct.unpack("<8I", key))
    s += [counter]
    s += list(struct.unpack("<3I", nonce))
    x = s[:]
    for _ in range(10):
        chacha_qr(x, 0, 4, 8, 12); chacha_qr(x, 1, 5, 9, 13)
        chacha_qr(x, 2, 6, 10, 14); chacha_qr(x, 3, 7, 11, 15)
        chacha_qr(x, 0, 5, 10, 15); chacha_qr(x, 1, 6, 11, 12)
        chacha_qr(x, 2, 7, 8, 13); chacha_qr(x, 3, 4, 9, 14)
    return struct.pack("<16I", *[(x[i] + s[i]) & 0xFFFFFFFF for i in range(16)])


# RFC 8439 §2.3.2: the anchor. Key 00..1f, nonce 00:00:00:09:00:00:00:4a:00:00:00:00, counter 1.
RFC_KEY = bytes(range(32))
RFC_NONCE = bytes.fromhex("000000090000004a00000000")
RFC_BLOCK_PREFIX = bytes.fromhex("10f1e7e4d13b5915500fdd1fa32071c4")
assert chacha_block(RFC_KEY, 1, RFC_NONCE)[:16] == RFC_BLOCK_PREFIX, "the Python Chacha20 does not match RFC 8439"


def transcription_stream(key, counter, nonce, length):
    stream = b""
    c = counter
    while len(stream) < length:
        stream += chacha_block(key, c & 0xFFFFFFFF, nonce)
        c += 1
    return stream[:length]


def reference_stream(key, counter, nonce, length):
    """The keystream from the `cryptography` package when it is installed —
    an implementation nobody in this house wrote — cross-checked against the
    transcription above; the transcription alone otherwise. Its ChaCha20
    takes a 16-byte nonce: the 32-bit little-endian counter, then RFC 8439's
    12-byte nonce."""
    ours = transcription_stream(key, counter, nonce, length)
    try:
        from cryptography.hazmat.primitives.ciphers import Cipher, algorithms
    except ImportError:
        return ours
    full = struct.pack("<I", counter & 0xFFFFFFFF) + nonce
    theirs = Cipher(algorithms.ChaCha20(key, full), mode=None).encryptor().update(bytes(length))
    assert theirs == ours, "the transcription and the cryptography package disagree"
    return theirs


def c_bytes(b):
    return "{" + ",".join(f"0x{x:02x}" for x in b) + ("" if b else "0") + "}"


def emit_pool_harness(path):
    """Compose the pool harness: stubs, this repo's hooks file, random.c with
    its includes stripped, then the tests — one translation unit so the
    tests can see the pool's statics."""
    from pathlib import Path
    root = Path(__file__).resolve().parents[1]

    def stripped(rel):
        return "\n".join(l for l in (root / rel).read_text().splitlines()
                         if not l.startswith("#include")) + "\n"

    stubs = '''#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "crypto/blake2s.h"
#include "crypto/chacha20.h"
#include "crypto/wipe.h"
#define TICKS_PER_SECOND 100
#define DEBUG_BOOT 0
#define printd(...) ((void)0)
typedef volatile uint32_t spinlock_t;
static uint64_t spinlock_acquire_irqsave(spinlock_t *l) { if (*l) abort(); *l = 1; return 0; }
static void spinlock_release_irqrestore(spinlock_t *l, uint64_t f) { (void)f; if (!*l) abort(); *l = 0; }
static uint64_t kTicksSinceStart;
'''
    with open(path, "w") as f:
        f.write(stubs)
        f.write(stripped("tools/test_random_pool_host.c"))
        f.write(stripped("kernel/include/random.h"))
        f.write(stripped("kernel/src/random.c"))
        f.write(stripped("tools/test_random_pool_host_tests.c"))


def main():
    if sys.argv[1] == "--pool":
        emit_pool_harness(sys.argv[2])
        return
    out = open(sys.argv[1], "w")
    rng = random.Random(0x5EED)
    out.write("// generated by tools/test_random_host.py — do not edit\n")
    cases = []
    for length in list(range(0, 130)) + [191, 192, 193, 255, 256, 257, 1000, 4096]:
        msg = bytes(rng.getrandbits(8) for _ in range(length))
        for keylen in (0, 1, 16, 32):
            key = bytes(rng.getrandbits(8) for _ in range(keylen))
            for outlen in (32, 16, 1):
                d = hashlib.blake2s(msg, digest_size=outlen, key=key).digest()
                cases.append((msg, key, outlen, d))
    out.write(f"#define BLAKE2S_CASES {len(cases)}\n")
    out.write("static const struct { const uint8_t* msg; size_t msglen; const uint8_t* key; size_t keylen; size_t outlen; const uint8_t* digest; } kBlake2sCases[] = {\n")
    blobs = []
    for i, (msg, key, outlen, d) in enumerate(cases):
        blobs.append(f"static const uint8_t b2m{i}[] = {c_bytes(msg)};")
        blobs.append(f"static const uint8_t b2k{i}[] = {c_bytes(key)};")
        blobs.append(f"static const uint8_t b2d{i}[] = {c_bytes(d)};")
    out.write("};\n")
    # rewrite: blobs first, then the table (C needs the arrays declared before use)
    out.seek(0); out.truncate()
    out.write("// generated by tools/test_random_host.py — do not edit\n")
    out.write("\n".join(blobs) + "\n")
    out.write(f"#define BLAKE2S_CASES {len(cases)}\n")
    out.write("static const struct { const uint8_t* msg; size_t msglen; const uint8_t* key; size_t keylen; size_t outlen; const uint8_t* digest; } kBlake2sCases[] = {\n")
    for i, (msg, key, outlen, d) in enumerate(cases):
        out.write(f"  {{ b2m{i}, {len(msg)}, b2k{i}, {len(key)}, {outlen}, b2d{i} }},\n")
    out.write("};\n")

    chacha = []
    chacha.append((RFC_KEY, 1, RFC_NONCE, 64))
    for i in range(24):
        key = bytes(rng.getrandbits(8) for _ in range(32))
        nonce = bytes(rng.getrandbits(8) for _ in range(12))
        counter = rng.getrandbits(32)
        length = rng.choice([1, 63, 64, 65, 128, 200, 1024])
        chacha.append((key, counter, nonce, length))
    for i, (key, counter, nonce, length) in enumerate(chacha):
        stream = reference_stream(key, counter, nonce, length)
        out.write(f"static const uint8_t ccK{i}[] = {c_bytes(key)};\n")
        out.write(f"static const uint8_t ccN{i}[] = {c_bytes(nonce)};\n")
        out.write(f"static const uint8_t ccS{i}[] = {c_bytes(stream)};\n")
    out.write(f"#define CHACHA_CASES {len(chacha)}\n")
    out.write("static const struct { const uint8_t* key; uint32_t counter; const uint8_t* nonce; const uint8_t* stream; size_t len; } kChachaCases[] = {\n")
    for i, (key, counter, nonce, length) in enumerate(chacha):
        out.write(f"  {{ ccK{i}, {counter}u, ccN{i}, ccS{i}, {length} }},\n")
    out.write("};\n")
    out.close()


if __name__ == "__main__":
    main()
