// test_math_host.c — libmath's corpus and state checks, run on the host.
//
// Built by tools/test_math_host.sh against objects compiled from the pinned
// musl sources and libmath's sqrt adapter, with no host libm on the link
// line: the script checks that every maths symbol in this binary is
// DEFINED in it, so no call can quietly land in glibc instead.
//
//   test_math_host vectors          every vector as "name i x y result",
//                                   hex bits, for the MPFR oracle
//   test_math_host expected         userland/tests/mathtest/expected.h
//   test_math_host state            the floating-point state checks
//   test_math_host dump <fn> <blk>  one block, to set beside the guest's
//                                   dump when a digest disagrees
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>                     // os64's, from userland/libmath/include

#define MATH_REPORT(...) printf(__VA_ARGS__)
#include "corpus.h"
#include "state.h"

static void print_vector(int f, int i)
{
    uint64_t x, y;
    math_vector(f, i, &x, &y);
    printf("%s %d %016llx %016llx %016llx\n", kMathFns[f].name, i, (unsigned long long)x,
           (unsigned long long)y, (unsigned long long)math_result(f, x, y));
}

static int find_fn(const char *name)
{
    for (int f = 0; f < MATH_FN_COUNT; f++)
        if (strcmp(kMathFns[f].name, name) == 0)
            return f;
    return -1;
}

int main(int argc, char **argv)
{
    const char *mode = argc > 1 ? argv[1] : "";
    if (strcmp(mode, "vectors") == 0) {
        for (int f = 0; f < MATH_FN_COUNT; f++)
            for (int i = 0; i < math_vector_count(&kMathFns[f]); i++)
                print_vector(f, i);
        return 0;
    }
    if (strcmp(mode, "expected") == 0) {
        int total = 0;
        for (int f = 0; f < MATH_FN_COUNT; f++)
            total += math_vector_count(&kMathFns[f]);
        printf("// expected.h — GENERATED by tools/test_math_host.sh --regen. Do not edit.\n"
               "//\n"
               "// One FNV-1a digest per block of %d vectors, per function, in corpus.h's\n"
               "// order, computed by the host build of the pinned source. The guest\n"
               "// fixture recomputes them through libmath.so; the host test fails if this\n"
               "// file no longer matches what the host build produces.\n"
               "#define MATH_EXPECTED_VECTORS %d\n"
               "static const uint64_t kMathExpected[] = {\n", MATH_BLOCK, total);
        for (int f = 0; f < MATH_FN_COUNT; f++) {
            printf("    // %s: %d vectors\n", kMathFns[f].name, math_vector_count(&kMathFns[f]));
            for (int b = 0; b < math_block_count(&kMathFns[f]); b++)
                printf("    0x%016llxull,\n", (unsigned long long)math_block_digest(f, b));
        }
        printf("};\n");
        return 0;
    }
    if (strcmp(mode, "state") == 0) {
        int failures = math_state_checks();
        printf("state: %s (%d failures)\n", failures ? "FAIL" : "PASS", failures);
        return failures ? 1 : 0;
    }
    if (strcmp(mode, "dump") == 0 && argc == 4) {
        int f = find_fn(argv[2]), b = atoi(argv[3]);
        if (f < 0 || b < 0 || b >= math_block_count(&kMathFns[f])) {
            fprintf(stderr, "no block %s %s\n", argv[2], argv[3]);
            return 2;
        }
        int end = (b + 1) * MATH_BLOCK, n = math_vector_count(&kMathFns[f]);
        for (int i = b * MATH_BLOCK; i < end && i < n; i++)
            print_vector(f, i);
        return 0;
    }
    fprintf(stderr, "usage: %s vectors | expected | state | dump <fn> <block>\n", argv[0]);
    return 2;
}
