#!/bin/bash
# Drive libfetch's driver against a scripted peer under the sanitizers: hop
# chains, downgrades, cut bodies, silent peers, cancellation, proxies, the
# body caps, every reply on three chunkings. tools/test_fetch_host.c says how.
#
# The gzip fixtures are made here by Python's gzip, the reference the guest
# decoder was diffed against in tools/test_gzip_host.sh, so a wrong byte is
# libfetch's and not the fixture's.

set -eu
cd "$(git rev-parse --show-toplevel)"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

python3 - "$work" <<'PY'
import gzip, pathlib, sys
work = pathlib.Path(sys.argv[1])
plain = b"hello gzip world\n" * 40
hello = gzip.compress(plain, compresslevel=9, mtime=0)
bomb  = gzip.compress(b"\0" * (2 * 1024 * 1024), compresslevel=9, mtime=0)
def arr(name, data):
    body = ",".join(str(b) for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{{body}}};\n"
out = "// GENERATED by tools/test_fetch_host.sh — do not edit.\n"
out += arr("GZ_HELLO", hello)
out += "static const char GZ_HELLO_PLAIN[] = " + '"' + plain.decode().replace("\n", "\\n") + '";\n'
out += arr("GZ_BOMB", bomb)
(work / "fixtures.h").write_text(out)
print(f"fixtures: hello {len(hello)} bytes gzip of {len(plain)}, bomb {len(bomb)} bytes gzip of 2 MiB")
PY

cc -std=c11 -g -Wall -Wextra -Werror -fsanitize=address,undefined \
   -fno-sanitize-recover=all \
   -I "$work" -I userland/libfetch/include -I userland/libfetch \
   -I userland/libtls/include -I userland/libgzip/include \
   -I userland/libos64/include -I abi/include \
   tools/test_fetch_host.c \
   userland/libfetch/fetch.c userland/libfetch/http.c \
   userland/libfetch/transport.c userland/libfetch/proxy.c \
   userland/libos64/url.c userland/libos64/str.c userland/libos64/fmt.c \
   userland/libos64/crc32.c \
   userland/libgzip/inflate.c userland/libgzip/deflate.c userland/libgzip/gzip.c \
   -o "$work/test_fetch"

ASAN_OPTIONS=detect_leaks=1 "$work/test_fetch" 12345
ASAN_OPTIONS=detect_leaks=1 "$work/test_fetch" "$(date +%s)"
